### ISSUE TITLE
i tried to import it in studio 

### ISSUE THREAD

**Issue by Toqeer12** [dhruv2601/Business-Card-Scanner#1]
i try to import it in studio and getting this error:
Error:Could not find com.android.tools.build:gradle:2.2.2.
Searched in the following locations:
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/2.2.2/gradle-2.2.2.pom
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/2.2.2/gradle-2.2.2.jar
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.2/gradle-2.2.2.pom
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.2/gradle-2.2.2.jar
Required by:
    project :tess-two
dont know how to resolve it.
Regards.

**Comment by dhruv2601** [comment]
Hey @Toqeer12 
It seems to be a simple gradle build problem, in [build.gradle](https://github.com/dhruv2601/Business-Card-Scanner/blob/master/libraries/tess-two/build.gradle) file try replacing mavenCentral() with jcenter().
Tell me if that is working.

**Comment by Toqeer12** [comment]
its already jcenter().

**Comment by Toqeer12** [comment]
now it resolve by changing the gradle version 2.2.2 to 2.3.1 but getting crash on click of the flash button 
here are the logs. Process: businesscard.dhruv.businesscardscanner, PID: 21248
                                                                                        java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/businesscard.dhruv.businesscardscanner-2/base.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-2/split_lib_dependencies_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-2/split_lib_slice_0_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-2/split_lib_slice_1_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-2/split_lib_slice_2_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-2/split_lib_slice_3_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-2/split_lib_slice_4_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-2/split_lib_slice_5_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-2/split_lib_slice_6_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-2/split_lib_slice_7_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-2/split_lib_slice_8_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/businesscard.dhruv.businesscardscanner-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libnative-lib.so"
                                                                                            at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                                            at java.lang.System.loadLibrary(System.java:989)
                                                                                            at businesscard.dhruv.businesscardscanner.MainActivity.<clinit>(MainActivity.java:52)
                                                                                            at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                            at java.lang.Class.newInstance(Class.java:1650)
                                                                                            at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855)
                                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:181)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:145)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6117)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by Toqeer12** [comment]
crash on extracting information
FATAL EXCEPTION: AsyncTask #1
                                                                                        Process: businesscard.dhruv.businesscardscanner, PID: 15347
                                                                                        java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                            at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                                         Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/businesscard.dhruv.businesscardscanner-1/base.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-1/split_lib_dependencies_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-1/split_lib_slice_0_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-1/split_lib_slice_1_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-1/split_lib_slice_2_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-1/split_lib_slice_3_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-1/split_lib_slice_4_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-1/split_lib_slice_5_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-1/split_lib_slice_6_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-1/split_lib_slice_7_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-1/split_lib_slice_8_apk.apk", zip file "/data/app/businesscard.dhruv.businesscardscanner-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/businesscard.dhruv.businesscardscanner-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libjpgt.so"
                                                                                            at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                                            at java.lang.System.loadLibrary(System.java:989)
                                                                                            at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:44)
                                                                                            at businesscard.dhruv.businesscardscanner.SaveCardActivity$extractOCR.doInBackground(SaveCardActivity.java:809)
                                                                                            at businesscard.dhruv.businesscardscanner.SaveCardActivity$extractOCR.doInBackground(SaveCardActivity.java:792)
                                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                            at java.lang.Thread.run(Thread.java:818) 
05-17 13:07:23.754 870-17492/? E/android.os.Debug: !@Dumpstate > sdumpstate -k -t -z -d -o /data/log/dumpstate_app_error
05-17 13:07:24.084 15347-15347/businesscard.dhruv.businesscardscanner E/WindowManager: android.view.WindowLeaked: Activity businesscard.dhruv.businesscardscanner.SaveCardActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{147b6cb7 V.E..... R......D 0,0-668,332} that was originally added here
                                                                                           at android.view.ViewRootImpl.<init>(ViewRootImpl.java:479)
                                                                                           at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:277)
                                                                                           at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                                                           at android.app.Dialog.show(Dialog.java:312)
                                                                                           at businesscard.dhruv.businesscardscanner.SaveCardActivity$extractOCR.onPreExecute(SaveCardActivity.java:802)
                                                                                           at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:587)
                                                                                           at android.os.AsyncTask.execute(AsyncTask.java:535)
                                                                                           at businesscard.dhruv.businesscardscanner.SaveCardActivity.onCreate(SaveCardActivity.java:470)
                                                                                           at android.app.Activity.performCreate(Activity.java:6374)
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855)
                                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:181)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:145)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6117)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.j

**Comment by dhruv2601** [comment]
Have you granted all the permissions? because the crashing is taking place in the SaveCardActivity and this happens when either you have stopped the Training Data downloading in between or the permissions have not been granted.

**Comment by bhavishavidja** [comment]
Can you please elaborate which permission need to Add for Training Data downloading?

**Comment by dhruv2601** [comment]
@bhavishavidja  WRITE_EXTERNAL_STORAGE should be granted for downloading the trained data and weights. To check if you already have it, you can look out for **eng.traineddata** in your file explorer.

Are you also having problems with the data downloading?

**Comment by bhavishavidja** [comment]
I'm getting this error 
FATAL EXCEPTION: AsyncTask #1
                                                                                      Process: businesscard.dhruv.businesscardscanner, PID: 4607
                                                                                      java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                          at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                                       Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/businesscard.dhruv.businesscardscanner-2/base.apk"],nativeLibraryDirectories=[/data/app/businesscard.dhruv.businesscardscanner-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libjpgt.so"
                                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                                          at java.lang.System.loadLibrary(System.java:988)
                                                                                          at businesscard.dhruv.businesscardscanner.SaveCardActivity$extractOCR.doInBackground(SaveCardActivity.java:812)
                                                                                          at businesscard.dhruv.businesscardscanner.SaveCardActivity$extractOCR.doInBackground(SaveCardActivity.java:793)
                                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                          at java.lang.Thread.run(Thread.java:818)

**Comment by bhavishavidja** [comment]
Hey
Can you please help me short this out ?
I'm getting this error
 FATAL EXCEPTION: AsyncTask #1
                                                 Process:
businesscard.dhruv.businesscardscanner, PID: 8100

java.lang.RuntimeException: An error occured while executing
doInBackground()
                                                     at
android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                     at
java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                     at
java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                     at
java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                     at
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                     at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at
java.lang.Thread.run(Thread.java:818)
                                                  Caused by:
java.lang.UnsatisfiedLinkError:
dalvik.system.PathClassLoader[DexPathList[[zip file
"/data/app/businesscard.dhruv.businesscardscanner-1/base.apk"],nativeLibraryDirectories=[/data/app/businesscard.dhruv.businesscardscanner-1/lib/arm,
/vendor/lib, /system/lib]]] couldn't find "libjpgt.so"
                                                     at
java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                     at
java.lang.System.loadLibrary(System.java:988)
                                                     at
com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:44)
                                                     at
businesscard.dhruv.businesscardscanner.SaveCardActivity$extractOCR.doInBackground(SaveCardActivity.java:817)
                                                     at
businesscard.dhruv.businesscardscanner.SaveCardActivity$extractOCR.doInBackground(SaveCardActivity.java:793)
                                                     at
android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                     at
java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                     at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

                                                     at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

                                                     at
java.lang.Thread.run(Thread.java:818)

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Thanks & Regards

Bhavisha Vidja
Android Developer

M : 9867170689
